version: '2'

services:
  bank.upcgold.io:
    environment:
      - VIRTUAL_HOST=bank.upcgold.io
      - LETSENCRYPT_HOST=bank.upcgold.io
    build: .
    image: mountain/upcgold.io
    container_name: bank.upcgold.io
    ports:
      # strapi runs on port 1337, so map this port out to port 7002 to access it.  the container always
      # specifies this it exposes this port in the Dockerfile.  to change this port (1337), change Dockerfile
      - 3000:3000
    networks:
      - mongonet
    restart: always

networks:
  mongonet:
    external: true
